### ISSUE TITLE
Key error when extracting samples

### ISSUE THREAD

**Issue by jvines** [nespinoza/juliet#10]
Hi @nespinoza, @dianadianadiana 

I have this error with Juliet when it finishes running:

Traceback (most recent call last):
  File "juliet.py", line 1410, in <module>
    utils.writepp(outpp,out)
  File "/Users/jvines/github/juliet/utils.py", line 250, in writepp
    omega = posteriors['posterior_samples']['omega_'+planet]*np.pi/180.
KeyError: 'omega_p1'

It's weird that it tried to access omega_p1 since I have it as fixed in my priors. If I try running it again, it tries to extract the parameters and I get the following:

Traceback (most recent call last):
  File "juliet.py", line 1399, in <module>
    priors[pname]['cvalue'] = np.median(out['posterior_samples'][pname])
KeyError: 'p_p1'

I'm guessing the second happens because of the first error, but it's still weird nonetheless.

Cheers,

Jose Vines.

**Comment by jvines** [comment]
After updating juliet to the latest version, this problem vanished (yay) so I'll just close this...
