### ISSUE TITLE
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8de7419d0>

### ISSUE THREAD

**Issue by Hiyabiswas** [nespinoza/juliet#108]
When I was trying to extract light curves using JULIET for TESS data and typed this command: 
results = dataset.fit(n_live_points=5000), then this error came:

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 5000
 dimensionality =    4
 *****************************************************

Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x7fc8dbea73a0>
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 1354, in loglike
    self.lc.generate(self.posteriors)
  File "/home/sbiswas/anaconda3/lib/python3.9/site-packages/juliet/fit.py", line 3415, in generate_lc_model
    parameter_values['sigma_w_' + self.sigmaw_iname[instrument]] * 1e-6)**2
KeyError: 'TESS26'...

Can anyone pls help me regarding this?

**Comment by nespinoza** [comment]
This sounds like a problem with the prior file. Can you post that?

**Comment by nespinoza** [comment]
Closing due to lack of response. Feel free to open another ticket!
