### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hover2pi** [nespinoza/juliet#34]
I tried pip installing and doing a local install but both throw the error `AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'`. It looks like perhaps it's a problem with the `radvel` package? I'm using Python 3.5.3. Have you seen this before? Thanks!

**Comment by nespinoza** [comment]
Hey @hover2pi! This is a first (for me) --- never seen this error before. Have you checked this is a `radvel` problem? Could you post the entire Traceback? If it is, best would be to ask them directly in their Github about this (https://github.com/California-Planet-Search/radvel/issues).

**Comment by hover2pi** [comment]
Here's the traceback:

```
Processing dependencies for juliet==2.0.24
Searching for radvel
Reading https://pypi.org/simple/radvel/
Downloading https://files.pythonhosted.org/packages/f3/99/953eca5e16444ac5098a68bbe5a92ee45294957a12cfbdb5a0caf6a974c7/radvel-1.4.1.tar.gz#sha256=bc3361466d4f90b61f085851829c8b72ba075813f383f1bfca885862e42c1f56
Best match: radvel 1.4.1
Processing radvel-1.4.1.tar.gz
Writing /var/folders/n1/5kfqkrz12bz4v70jvvnrtlb80001rh/T/easy_install-g4yo3i_6/radvel-1.4.1/setup.cfg
Running radvel-1.4.1/setup.py -q bdist_egg --dist-dir /var/folders/n1/5kfqkrz12bz4v70jvvnrtlb80001rh/T/easy_install-g4yo3i_6/radvel-1.4.1/egg-dist-tmp-54htbq7l
/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Traceback (most recent call last):
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/n1/5kfqkrz12bz4v70jvvnrtlb80001rh/T/easy_install-g4yo3i_6/radvel-1.4.1/setup.py", line 48, in <module>
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/var/folders/n1/5kfqkrz12bz4v70jvvnrtlb80001rh/T/easy_install-g4yo3i_6/radvel-1.4.1/setup.py", line 10, in finalize_options
    packages=['juliet'],
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by hover2pi** [comment]
Ok! In the `exoctk` environment, I had to upgrade to:

```
Cython==0.25.2
d2to1==0.2.12.post1
jupyter_client==6.1.6
jupyter_core==4.6.3
werkzeug==0.16.1
pyyaml==5.1.0
```

Then install `radvel` separately and then `juliet` installed! This just means we need to update the requirements in the `exoctk` environment to the versions listed above to include `juliet` as a dependency. So I'm good to go!
